[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
PaleobiologyDB = "c9cb2f45-518b-476d-9b58-4dd79871b05b"
PhyloPicMakie = "29f7fcc2-58b8-448e-949b-ed9dd2d8a249"

[sources]
PaleobiologyDB = {path = ".."}
PhyloPicMakie = {path = "../deps/PhyloPicMakie.jl"}

[compat]
Documenter = "1"
